name: CI/CD - FastAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tags
        id: vars
        run: echo "SHA_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/does-not-compile/portfolio-chatbot:latest \
                       -t ghcr.io/does-not-compile/portfolio-chatbot:${SHA_TAG} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/does-not-compile/portfolio-chatbot:latest
          docker push ghcr.io/does-not-compile/portfolio-chatbot:${SHA_TAG}

  deploy:
    name: Deploy to EC2
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: SSH & Deploy FastAPI container
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/app

            # --- Get currently running FastAPI image ---
            PREV_IMAGE=$(docker inspect --format='{{.Config.Image}}' fastapi-app)

            # --- Pull new image ---
            echo "Pulling new FastAPI image..."
            docker-compose pull fastapi

            # --- Deploy new image ---
            echo "Stopping old container if exists..."
            docker stop fastapi-app || true
            docker rm fastapi-app || true

            echo "Starting FastAPI container with new image..."
            docker-compose up -d fastapi

            # --- Health check ---
            echo "Checking FastAPI health..."
            for i in {1..10}; do
              sleep 3
              if curl -fsS http://localhost:8000/health; then
                echo "✅ FastAPI is healthy!"

                echo "Promoting new image to stable..."
                docker tag ghcr.io/does-not-compile/portfolio-chatbot:${SHA_TAG} \
                           ghcr.io/does-not-compile/portfolio-chatbot:stable
                docker push ghcr.io/does-not-compile/portfolio-chatbot:stable

                echo "Cleaning up old images, volumes, and networks..."
                docker image prune -af
                docker volume prune -f
                docker network prune -f
                exit 0
              fi
            done

            # --- Rollback ---
            echo "❌ FastAPI failed health check, rolling back to previous image: $PREV_IMAGE"
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            docker run -d --name fastapi-app --network app_proxy -p 8000:8000 $PREV_IMAGE

            exit 1
