name: CI/CD - FastAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tags
        id: vars
        run: echo "SHA_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/<your-username>/<repo-name>:latest \
                       -t ghcr.io/<your-username>/<repo-name>:${SHA_TAG} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/<your-username>/<repo-name>:latest
          docker push ghcr.io/<your-username>/<repo-name>:${SHA_TAG}

  deploy:
    name: Deploy to EC2
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: SSH & Deploy FastAPI container
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/myproject
            echo "Pulling new FastAPI image (SHA: ${{ env.SHA_TAG }})..."
            docker-compose pull fastapi
            echo "Restarting FastAPI service..."
            docker-compose up -d fastapi
            docker-compose ps fastapi
